services:
  mysql-db:
    image: mysql:latest
    ports:
    - 3306:3306
    volumes:
    - mysql-db-vol:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=12345678
  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql-db
      - PMA_PORT=3306

volumes:
  mysql-db-vol: