# Este exemplo executa dois containers
# Um container do banco mysql e outro do phpmyadmin
# PHPMyAdmin é uma ferramenta para gerenciar bancos de dados
# Mysql de forma fácil
#
# Rede 'net-mysql'
# ______________________________________________________
#|   __________                   _____________        |
#|   \  mysql  \- 3306 <--------- \ phpmyadmin \-80    |
#|    \_________\                  \____________\      |
#|   /var/lib/mysql                                    |
#|        |                                            |
#|   (volume-mysql)                                    |
#|_____________________________________________________|
#
# Executando este exemplo:
# $ docker compose -f phpmyadmin.yml up -d
version: "3.8"
services:
  mysql:
    image: mariadb
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.test
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
     - ./mysql:/var/lib/mysql
     - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - net-mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    ports:
      - "3000:80"
    environment:
      PMA_HOST: "mysql"
      PMA-PORT: "3306"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - net-mysql
    restart: always
networks:
  net-mysql:
    name: "${NETWORK}"
    external: true