FROM erickweil/container-vm

# create_user.sh
ENV USERNAME=usuario
ENV PASSWORD=senha

# code-server
ENV DEFAULT_WORKSPACE=/home/usuario

COPY . .
RUN chmod +x *.sh && \
	/bin/bash ./create_user.sh

	
# Para realizar build
# docker build -f Dockerfile.user -t erickweil/container-vm:usuario .
# Executar container:
# docker rm -f vm-usuario && docker run -d --name vm-usuario -p 3000:22 -p 3001:8080 --privileged erickweil/container-vm:usuario