services:
  # https://github.com/clemens33/minio/tree/master
  # http://www.sefidian.com/2022/04/08/deploy-standalone-minio-using-docker-compose/
  minio:
    container_name: minio
    image: erickweil/minio-simple-iam:latest
    # build: .
    volumes:
      - "${MINIO_VOLUME:-vol-minio}:/data"
    ports:
      - "${MINIO_SERVER_EXPOSE_PORT}:9000"
      - "${MINIO_CONSOLE_EXPOSE_PORT}:9001"
    environment:
      MINIO_URL: "http://localhost:9000"
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_USER: "${MINIO_USER}"
      MINIO_PASSWORD: "${MINIO_PASSWORD}"
      BUCKET_NAME: "${BUCKET_NAME}"
      BUCKET_ACCESS_KEY: "${BUCKET_ACCESS_KEY}"
      BUCKET_SECRET_KEY: "${BUCKET_SECRET_KEY}"

volumes:
  vol-minio: